interval = 10
splay = 1
splay_first_run = 0
run_lock_timeout = 1800
log_level = "warn"
env_path_prefix = ";C:/WINDOWS;C:/WINDOWS/system32/;C:/WINDOWS/system32/WindowsPowerShell/v1.0;C:/ProgramData/chocolatey/bin"
ssl_verify_mode = ":verify_peer"

[chef_license]
acceptance = "undefined"

[automate]
enable = false
server_url = "https://<automate_url>"
token = "<automate_token>"
user = "<automate_user>"